# Generated by Django 5.1.1 on 2025-05-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestion',
            name='question_text',
            field=models.CharField(default='free question', max_length=500),
        ),
    ]
