# Generated by Django 5.1.1 on 2025-05-19 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_examquestion_question_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examchoice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.examquestion'),
        ),
    ]
