# Generated by Django 5.1.1 on 2025-05-21 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_exam_id_alter_exam_title'),
        ('questions', '0003_alter_examchoice_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examquestion',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.exam'),
        ),
    ]
