# Generated by Django 5.2.1 on 2025-05-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='department',
            field=models.CharField(max_length=255),
        ),
    ]
