# Generated by Django 5.1.1 on 2025-05-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='id',
        ),
        migrations.AlterField(
            model_name='exam',
            name='title',
            field=models.SlugField(primary_key=True, serialize=False),
        ),
    ]
